//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class AddressVerify {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText email;
        protected System.Web.UI.HtmlControls.HtmlInputText street;
        protected System.Web.UI.HtmlControls.HtmlInputText zip;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submit;
    }
}
