//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class DoDirectPayment {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText firstName;
        protected System.Web.UI.HtmlControls.HtmlInputText lastName;
        protected System.Web.UI.WebControls.DropDownList creditCardType;
        protected System.Web.UI.HtmlControls.HtmlInputText creditCardNumber;
        protected System.Web.UI.WebControls.Calendar calDate;
        protected System.Web.UI.WebControls.TextBox cardExpiryDate;
        protected System.Web.UI.HtmlControls.HtmlInputText cvv2Number;
        protected System.Web.UI.WebControls.DropDownList paymentType;
        protected System.Web.UI.HtmlControls.HtmlInputText amount;
        protected System.Web.UI.WebControls.DropDownList currencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText payerName;
        protected System.Web.UI.HtmlControls.HtmlInputText street1;
        protected System.Web.UI.HtmlControls.HtmlInputText street2;
        protected System.Web.UI.HtmlControls.HtmlInputText city;
        protected System.Web.UI.HtmlControls.HtmlInputText state;
        protected System.Web.UI.HtmlControls.HtmlInputText postalCode;
        protected System.Web.UI.HtmlControls.HtmlInputText country;
        protected System.Web.UI.HtmlControls.HtmlInputText phone;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submitBtn;
    }
}
