//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class DoReferenceTransaction {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText referenceId;
        protected System.Web.UI.WebControls.DropDownList currencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingTotal;
        protected System.Web.UI.HtmlControls.HtmlInputText insuranceTotal;
        protected System.Web.UI.HtmlControls.HtmlInputText handlingTotal;
        protected System.Web.UI.HtmlControls.HtmlInputText taxTotal;
        protected System.Web.UI.HtmlControls.HtmlTextArea orderDescription;
        protected System.Web.UI.WebControls.DropDownList paymentAction;
        protected System.Web.UI.HtmlControls.HtmlInputText itemName;
        protected System.Web.UI.HtmlControls.HtmlInputText itemAmount;
        protected System.Web.UI.HtmlControls.HtmlInputText itemQuantity;
        protected System.Web.UI.HtmlControls.HtmlInputText salesTax;
        protected System.Web.UI.WebControls.DropDownList itemCategory;
        protected System.Web.UI.HtmlControls.HtmlInputText itemDescription;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submit;
    }
}
