//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class RefundTransaction {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText transactionId;
        protected System.Web.UI.WebControls.DropDownList refundType;
        protected System.Web.UI.HtmlControls.HtmlInputText refundAmount;
        protected System.Web.UI.WebControls.DropDownList currencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText memo;
        protected System.Web.UI.WebControls.Calendar calDate;
        protected System.Web.UI.WebControls.TextBox retryUntil;
        protected System.Web.UI.WebControls.DropDownList refundSource;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submitBtn;
    }
}
