//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class SetCustomerBillingAgreement {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText buyerEmail;
        protected System.Web.UI.HtmlControls.HtmlInputText returnUrl;
        protected System.Web.UI.HtmlControls.HtmlInputText cancelUrl;
        protected System.Web.UI.HtmlControls.HtmlTextArea billingAgreementText;
        protected System.Web.UI.WebControls.DropDownList billingType;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submit;
    }
}
