//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class TransactionSearch {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Calendar calStartDate;
        protected System.Web.UI.WebControls.TextBox startDate;
        protected System.Web.UI.WebControls.Calendar calEndDate;
        protected System.Web.UI.WebControls.TextBox endDate;
        protected System.Web.UI.HtmlControls.HtmlInputText payer;
        protected System.Web.UI.HtmlControls.HtmlInputText receiver;
        protected System.Web.UI.HtmlControls.HtmlInputText receiptId;
        protected System.Web.UI.HtmlControls.HtmlInputText transactionID;
        protected System.Web.UI.HtmlControls.HtmlInputText profileId;
        protected System.Web.UI.HtmlControls.HtmlInputText payerName;
        protected System.Web.UI.HtmlControls.HtmlInputText auctionItemNumber;
        protected System.Web.UI.HtmlControls.HtmlInputText invoiceID;
        protected System.Web.UI.HtmlControls.HtmlInputText cardNumber;
        protected System.Web.UI.WebControls.DropDownList transactionClass;
        protected System.Web.UI.HtmlControls.HtmlInputText amount;
        protected System.Web.UI.WebControls.DropDownList currencyCode;
        protected System.Web.UI.WebControls.DropDownList transactionStatus;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit Submit;
    }
}
