//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class BillUser {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText amount;
        protected System.Web.UI.WebControls.DropDownList currencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText mpId;
        protected System.Web.UI.WebControls.DropDownList paymentType;
        protected System.Web.UI.HtmlControls.HtmlInputText memo;
        protected System.Web.UI.HtmlControls.HtmlInputText emailSubject;
        protected System.Web.UI.HtmlControls.HtmlInputText tax;
        protected System.Web.UI.WebControls.DropDownList taxCurrencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText shipping;
        protected System.Web.UI.WebControls.DropDownList shippingCurrencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText handling;
        protected System.Web.UI.WebControls.DropDownList handlingCurrencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText itemName;
        protected System.Web.UI.HtmlControls.HtmlInputText itemNumber;
        protected System.Web.UI.HtmlControls.HtmlInputText invoiceNumber;
        protected System.Web.UI.HtmlControls.HtmlInputText custom;
        protected System.Web.UI.HtmlControls.HtmlInputText buttonSource;
        protected System.Web.UI.HtmlControls.HtmlInputText softDescriptor;
        protected System.Web.UI.WebControls.DropDownList returnFMFDetails;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submit;
    }
}
