//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class DoNonReferencedCredit {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText creditCardNumber;
        protected System.Web.UI.WebControls.Calendar calDate;
        protected System.Web.UI.WebControls.TextBox cardExpiryDate;
        protected System.Web.UI.WebControls.DropDownList creditCardType;
        protected System.Web.UI.HtmlControls.HtmlInputText cvv;
        protected System.Web.UI.HtmlControls.HtmlInputText comment;
        protected System.Web.UI.HtmlControls.HtmlInputText itemAmount;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingAMount;
        protected System.Web.UI.HtmlControls.HtmlInputText taxAmount;
        protected System.Web.UI.HtmlControls.HtmlInputText currencyId;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submitBtn;
    }
}
