//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class DoUATPAuthorization {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText uatpNumber;
        protected System.Web.UI.HtmlControls.HtmlInputText expMonth;
        protected System.Web.UI.HtmlControls.HtmlInputText expYear;
        protected System.Web.UI.HtmlControls.HtmlInputText amount;
        protected System.Web.UI.HtmlControls.HtmlInputText currencyID;
        protected System.Web.UI.WebControls.DropDownList transactionEntity;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submit;
    }
}
