//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class EnterBoarding {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText programCode;
        protected System.Web.UI.HtmlControls.HtmlInputText productList;
        protected System.Web.UI.HtmlControls.HtmlInputText partnerCustom;
        protected System.Web.UI.HtmlControls.HtmlInputText imageUrl;
        protected System.Web.UI.HtmlControls.HtmlInputText Text2;
        protected System.Web.UI.WebControls.DropDownList marketingCategory;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit Submit;
    }
}
