//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class MassPay {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText emailSubject;
        protected System.Web.UI.WebControls.DropDownList receiverType;
        protected System.Web.UI.HtmlControls.HtmlInputText emailId;
        protected System.Web.UI.HtmlControls.HtmlInputText phoneNumber;
        protected System.Web.UI.HtmlControls.HtmlInputText receiverId;
        protected System.Web.UI.HtmlControls.HtmlInputText amount;
        protected System.Web.UI.WebControls.DropDownList currencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText note;
        protected System.Web.UI.HtmlControls.HtmlInputText uniqueId;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submit;
    }
}
