//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class SetExpressCheckout {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText returnUrl;
        protected System.Web.UI.HtmlControls.HtmlInputText cancelUrl;
        protected System.Web.UI.HtmlControls.HtmlInputText buyerEmail;
        protected System.Web.UI.WebControls.DropDownList solutionType;
        protected System.Web.UI.WebControls.DropDownList reqConfirmShipping;
        protected System.Web.UI.WebControls.DropDownList noShipping;
        protected System.Web.UI.WebControls.DropDownList addressoverride;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingName;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingStreet1;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingStreet2;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingCity;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingState;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingPostalCode;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingCountry;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingPhone;
        protected System.Web.UI.WebControls.DropDownList currencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingTotal;
        protected System.Web.UI.HtmlControls.HtmlInputText insuranceTotal;
        protected System.Web.UI.HtmlControls.HtmlInputText handlingTotal;
        protected System.Web.UI.HtmlControls.HtmlInputText taxTotal;
        protected System.Web.UI.HtmlControls.HtmlTextArea orderDescription;
        protected System.Web.UI.WebControls.DropDownList paymentAction;
        protected System.Web.UI.HtmlControls.HtmlInputText itemName;
        protected System.Web.UI.HtmlControls.HtmlInputText itemAmount;
        protected System.Web.UI.HtmlControls.HtmlInputText itemQuantity;
        protected System.Web.UI.HtmlControls.HtmlInputText salesTax;
        protected System.Web.UI.WebControls.DropDownList itemCategory;
        protected System.Web.UI.HtmlControls.HtmlInputText itemDescription;
        protected System.Web.UI.HtmlControls.HtmlTextArea billingAgreementText;
        protected System.Web.UI.WebControls.DropDownList billingType;
        protected System.Web.UI.WebControls.DropDownList localeCode;
        protected System.Web.UI.HtmlControls.HtmlInputText pageStyle;
        protected System.Web.UI.HtmlControls.HtmlInputText cppheaderimage;
        protected System.Web.UI.HtmlControls.HtmlInputText cppheaderbordercolor;
        protected System.Web.UI.HtmlControls.HtmlInputText cppheaderbackcolor;
        protected System.Web.UI.HtmlControls.HtmlInputText cpppayflowcolor;
        protected System.Web.UI.HtmlControls.HtmlInputText brandName;
        protected System.Web.UI.WebControls.DropDownList allowNote;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submit;
    }
}
