//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class UpdateRecurringPaymentsProfile {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText profileId;
        protected System.Web.UI.HtmlControls.HtmlInputText note;
        protected System.Web.UI.HtmlControls.HtmlInputText subscriberName;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingName;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingStreet1;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingStreet2;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingCity;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingState;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingPostalCode;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingCountry;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingPhone;
        protected System.Web.UI.HtmlControls.HtmlInputText additionalBillingCycles;
        protected System.Web.UI.WebControls.DropDownList currencyCode;
        protected System.Web.UI.HtmlControls.HtmlInputText amount;
        protected System.Web.UI.HtmlControls.HtmlInputText outstandingBalance;
        protected System.Web.UI.HtmlControls.HtmlInputText maxFailedPayments;
        protected System.Web.UI.WebControls.DropDownList autoBillOutstandingAmount;
        protected System.Web.UI.WebControls.Calendar calDate;
        protected System.Web.UI.WebControls.TextBox billingStartDate;
        protected System.Web.UI.HtmlControls.HtmlInputText creditCardNumber;
        protected System.Web.UI.WebControls.DropDownList expMonth;
        protected System.Web.UI.WebControls.DropDownList expYear;
        protected System.Web.UI.HtmlControls.HtmlInputText cardOnName;
        protected System.Web.UI.WebControls.DropDownList creditCardType;
        protected System.Web.UI.HtmlControls.HtmlInputText cvv;
        protected System.Web.UI.HtmlControls.HtmlInputText trialBillingFrequency;
        protected System.Web.UI.WebControls.DropDownList trialBillingPeriod;
        protected System.Web.UI.HtmlControls.HtmlInputText trialBillingCycles;
        protected System.Web.UI.HtmlControls.HtmlInputText trialBillingAmount;
        protected System.Web.UI.HtmlControls.HtmlInputText trialShippingAmount;
        protected System.Web.UI.HtmlControls.HtmlInputText trialTaxAmount;
        protected System.Web.UI.HtmlControls.HtmlInputText billingFrequency;
        protected System.Web.UI.WebControls.DropDownList billingPeriod;
        protected System.Web.UI.HtmlControls.HtmlInputText totalBillingCycles;
        protected System.Web.UI.HtmlControls.HtmlInputText billingAmount;
        protected System.Web.UI.HtmlControls.HtmlInputText shippingAmount;
        protected System.Web.UI.HtmlControls.HtmlInputText taxAmount;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submitBtn;
    }
}
